[project]
name = "napari-pipeline"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.8,<3.9"

dependencies = [
    "napari[pyqt]",
    "numpy",
    "qtpy",
    "centrosome==1.2.3",
    "scipy",
    "h5py",
    "scikit-image",
    "Pillow",
    "future",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
napari_pipeline = ["napari.yaml", "config.json"]

[project.scripts]
napari-pipeline = "napari_pipeline._widget:PipelineWidget"

[project.entry-points."napari.manifest"]
napari-pipeline = "napari_pipeline:napari.yaml"
